name = "ericphillips-xyz-home"
compatibility_date = "2023-04-15"
routes = [
  "ericphillips.xyz",
  "ericphillips.xyz/"
]
kv_namespaces = [
  { binding = "TRAFFIC", id = "6408a3ae6678454f8528d8c3d7da63c2" }
]
main = "index.js"
